services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  server:
    build: ./server
    container_name: server
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
    environment:
      MONGO_URI: mongodb://mongodb:27017/elearning_db
    restart: unless-stopped

  client:
    build: ./client
    container_name: client
    ports:
      - "3000:80"
    depends_on:
      - server
    restart: unless-stopped

volumes:
  mongo-data:
